- src/timeseriesflattener/__init__.py
- src/timeseriesflattener/flattened_dataset.py
- src/timeseriesflattener/testing/utils_for_testing.py
- tests/test_timeseriesflattener/test_add_values.py
- tests/test_timeseriesflattener/test_errors.py
- tests/test_timeseriesflattener/test_flattened_dataset_generation.py
> refactor: rename main class

- src/timeseriesflattener/feature_spec_objects.py
- src/timeseriesflattener/flattened_dataset.py
- tests/test_timeseriesflattener/test_flattened_dataset/test_flattened_dataset.py
> Remove hardcoded timestamps

- src/timeseriesflattener/flattened_dataset.py
- tests/test_timeseriesflattener/test_flattened_dataset/test_flattened_dataset.py
> fix: don't let double compute duplicate columns

- src/timeseriesflattener/flattened_dataset.py
- tests/test_timeseriesflattener/test_flattened_dataset/test_add_values.py
> fix: static spec ignored outcome col name override

- .github/actions/test/action.yml
- .github/actions/test_tutorials/action.yml
- .github/workflows/documentation.yml
- .github/workflows/main_test_and_release.yml
- pyproject.toml
> build: remove poetry

- .github/workflows/documentation.yml
- docs/faq.rst
- docs/tutorials.rst
- pyproject.toml
- src/timeseriesflattener/column_handler.py
- src/timeseriesflattener/flattened_dataset.py
- src/timeseriesflattener/text_embedding_functions.py
> Fix-documentation

- .github/workflows/documentation.yml
> ci: fix documentation

- .codespellrc
- .github/workflows/codespell.yml
- CHANGELOG.md
- README.md
- docs/tutorials/01_basic.ipynb
- docs/tutorials/02_advanced.ipynb
- docs/tutorials/03_text.ipynb
- paper/paper.md
- src/timeseriesflattener/flattened_dataset.py
- src/timeseriesflattener/resolve_multiple_functions.py
- src/timeseriesflattener/testing/utils_for_testing.py
- src/timeseriesflattener/utils.py
- tests/test_timeseriesflattener/test_flattened_dataset/test_concatenation.py
- [N/A] I have assigned ranges (e.g. `>=0.1, <0.2`) to all new dependencies (allows dependabot to keep dependency ranges wide for better compatability)
typo in above will be fixed in this PR (unfortunately codespell ignores that folder by default and I did not bother adding it somehow to be considered but fed the file directly).
> codespell: config, workflow, typos fixed

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> docs: add contributor guidelines

- .gitignore
- pyproject.toml
- tests/test_data/flattened/generated_with_outcome/create_synth_flattened_with_outcome.py
- tests/test_data/raw/create_synth_prediction_times.py
- tests/test_data/raw/create_synth_raw_binary.py
- tests/test_data/raw/create_synth_raw_float.py
- tests/test_data/raw/create_synth_sex.py
> ci: loosen psycopmlutils deps

- .zenodo.json
- paper/paper.md
> Fix--add-.zenodo.json

- .codespellrc
- .flake8
- pyproject.toml
- src/timeseriesflattener/feature_spec_objects.py
- src/timeseriesflattener/flattened_dataset.py
- src/timeseriesflattener/logger.py
- tasks.py
- tests/test_timeseriesflattener/test_flattened_dataset/test_flattened_dataset.py
- tests/test_timeseriesflattener/test_flattened_dataset/utils.py
- tests/test_timeseriesflattener/test_utils.py
Had conflicting col names when doing feature set description. Moved all the logic to objects.
@HLasse, I've merged because it's a bugfix and I needed it, but please do make a review! Then I'll apply those changes in another branch.
> refactor: move all col name logic to objects

- .github/actions/test/action.yml
- .github/workflows/static_type_checks.yml
- pyproject.toml
- src/timeseriesflattener/feature_spec_objects.py
- tasks.py
- tests/test_timeseriesflattener/test_feature_spec_objects.py
> Fix: change type hints in specs to allow for floats in interval_days

- src/timeseriesflattener/resolve_multiple_functions.py
- tests/test_timeseriesflattener/test_resolve_multiple.py
two additional fns for text that summarises information at the text level
> additional text resolve_multiple fns

- src/timeseriesflattener/feature_spec_objects.py
- tests/test_timeseriesflattener/test_feature_spec_objects.py
Attempted to make a group spec for the TextPredictorSpec, since our feature gen scripts are currently very long and messy 🙃
> TextPredictorGroupSpec

- .github/workflows/documentation.yml
- pyproject.toml
- tests/test_timeseriesflattener/test_flattened_dataset/test_concatenation.py
Fixes failing tests due to an auto-upgraded pyright version.
> build: fix failing tests

- .github/workflows/documentation.yml
- pyproject.toml
- tasks.py
> fix: make docs render properly

- pyproject.toml
> fix: hopeful ci docs fix

- .github/workflows/documentation.yml
- pyproject.toml
Tried to fix problem raised in #295
> Fix documentation

- README.md
> update links to projects

- .github/workflows/documentation.yml
- .github/workflows/main_test_and_release.yml
- .github/workflows/pre-commit.yml
- .github/workflows/static_type_checks.yml
- pyproject.toml
- src/timeseriesflattener/flattened_dataset.py
- src/timeseriesflattener/utils/pydantic_basemodel.py
> refactor(#343): upgrade to pydantic v2

- src/timeseriesflattener/flattened_dataset.py
- src/timeseriesflattener/testing/utils_for_testing.py
- src/timeseriesflattener/tests/test_timeseriesflattener/test_flattened_dataset/test_add_values.py
> add insufficient look distance test

- .gitignore
- src/timeseriesflattener/testing/utils_for_testing.py
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
> tests(#362): add tests for each module

- src/timeseriesflattenerv2/aggregators.py
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
> feat(#359): handle fallbacks

- .github/actions/test/action.yml
- .github/workflows/static_type_checks.yml
- pyproject.toml
- tasks.py
> dev: remove tox

- src/timeseriesflattenerv2/aggregators.py
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
> feat(#360): ensure correct ordering before concatenating

- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
Fixes #373
Fixes #374
Fixes #375
> feat(#376): add prefix to colname

- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
> tests(#378): test using multiple features at once

- pyproject.toml
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
> feat(#383): process one feature at a time with progress bar

- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
> feat(#379): check that no value columns have the same name

- .github/workflows/benchmark.yml
- pyproject.toml
- src/test_benchmark.py
> feat(#384): add benchmark

- src/timeseriesflattenerv2/aggregators.py
feat: expand aggregators
update aggregators.py
> feat: expand aggregators

- src/test_benchmark.py
- src/timeseriesflattenerv2/_process_spec.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
> perf(#423): multiprocessing

- src/timeseriesflattenerv2/feature_specs.py
> feat(#402): allow eager polarsframes as input

- src/timeseriesflattenerv2/_process_spec.py
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/test_process_spec.py
> refactor(#403): rename slicedframe to timemaskedframe

- src/timeseriesflattenerv2/_process_spec.py
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/test_flattener.py
feat(#364): validate columns exist in ValueFrame
Fixes #364
feat: validate columns in valueframe
> feat(#364): validate columns exist in ValueFrame

- src/timeseriesflattenerv2/aggregators.py
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/test_aggregators.py
> feat(#396): add all aggregators from v1

- src/test_benchmark.py
- src/timeseriesflattenerv2/_process_spec.py
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
- src/timeseriesflattenerv2/test_process_spec.py
- src/timeseriesflattenerv2/test_specs.py
feat(#400): allow lookbehind tuple
Fixes #400
> feat(#400): allow lookbehind tuple

- src/timeseriesflattenerv2/aggregators.py
- src/timeseriesflattenerv2/test_aggregators.py
> fix(#447): implement earliest and latest without requiring sorting

- .vscode/settings.json
- src/timeseriesflattener/testing/test_data/models/create_bow_and_pca_model.py
- src/timeseriesflattenerv2/_process_spec.py
- src/timeseriesflattenerv2/feature_specs.py
- src/timeseriesflattenerv2/test_aggregators.py
- src/timeseriesflattenerv2/test_flattener.py
- src/timeseriesflattenerv2/test_process_spec.py
- tasks.py
> feat(#449): propagate timeseries column to aggregation function

- pyproject.toml
- requirements-dev.lock
- src/timeseriesflattener/feature_specs/group_specs.py
- src/timeseriesflattenerv2/from_legacy.py
- src/timeseriesflattenerv2/test_from_legacy.py
> feat(#425): support from_legacy api interface

- src/timeseriesflattenerv2/_intermediary_frames.py
- src/timeseriesflattenerv2/flattener.py
- src/timeseriesflattenerv2/test_flattener.py
> fix(#441): return entity_id in aggregated column

- src/timeseriesflattenerv2/feature_specs/timedelta.py
- src/timeseriesflattenerv2/spec_processors/test_temporal.py
- src/timeseriesflattenerv2/spec_processors/timedelta.py
Allows the user to specifiy what output format they want the TimeDelta feature to be
> feat: allow setting format in timedeltaspec

- docs/tutorials/04_from_legacy.ipynb
> docs(#477): add from_legacy tutorial

- README.md
- example.py
- src/timeseriesflattenerv2/__init__.py
> docs(#485): update readme to use v2

- src/timeseriesflattenerv2/_intermediary_frames.py
- src/timeseriesflattenerv2/feature_specs/meta.py
- src/timeseriesflattenerv2/feature_specs/outcome.py
- src/timeseriesflattenerv2/feature_specs/static.py
- src/timeseriesflattenerv2/feature_specs/timestamp_frame.py
> docs(#496): add some docstrings to user facing specs on the expected type of input and general usage

- docs/tutorials/04_from_legacy.ipynb
- src/timeseriesflattener/aggregators.py
docs(#511): add docstrings to aggregators
Fixes #511
docs: docstrings for aggregators
> docs(#511): add docstrings to aggregators

- docs/tutorials/01_basic.ipynb
- src/timeseriesflattener/feature_specs/outcome.py
feat(#515): make the output col name of BooleanOutcomeSpec user-definable
Fixes #515
fix: specify outcome colname in boolean
> feat(#515): make the output col name of BooleanOutcomeSpec user-definable

- src/timeseriesflattener/spec_processors/temporal.py
- src/timeseriesflattener/spec_processors/test_temporal.py
had forgotten to add step_size arg to step_size test and only realised as I merged with main 🙃 
found that 
1. still need that magical +2 instead of +1
2. "max" takes the highest number, so with lookbehinds it takes the shortest one (because they are minus) - added abs
> fix sliding window test

- src/timeseriesflattener/__init__.py
feat(#517): expose ValueSpecification
Fixes #517
fix: expose ValueSpecification
> feat(#517): expose ValueSpecification
